spring.application.name=workflow

# PostgreSQL Info
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=kwangs
spring.datasource.password=kwangs

# MyBatis Setting
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
logging.level.com.workflow.office.mapper=debug

# messages.properties
spring.messages.basename=message
# Encoding
spring.messages.encoding=UTF-8

# thymeleaf
spring.thymeleaf.cache=false